---
- hosts: MM_Vimodrone
  gather_facts: no
  connection: network_cli


  vars:
    ansible_network_os: ios
    
  tasks:

  - name: CONFIGURE BANNER ON CISCO DEVICES
    ios_banner:
      banner: login
      text: "          FUNZICA           "
      state: present

  - name: CONFIGURE HOSTNAME ON CISCO DEVICES
    ios_config:
       lines: hostname PORTA-DOWN-ALLARME
    
  - name: SHOW RUN | BEG BANNER 
    ios_command:
      commands:
        - show run | beg HODL
    register: banner

  - debug: var=banner.stdout_lines
